version: '3'

services:
    db:
        image: "postgres:12"
        restart: always
        environment:
            - POSTGRES_USER=proxy_py
            - POSTGRES_PASSWORD=proxy_py
            - POSTGRES_DB=proxy_py
        volumes:
            - pgdata:/home/user/proxy_py_postgres_data
    core:
        build: .
        ports:
            - "55555:55555"
        environment:
            - PROXY_PY_PROXY_PROVIDER_SERVER_ADDRESS="{'HOST':'0.0.0.0','PORT':55555}"
            - PROXY_PY_DATABASE_CONNECTION_KWARGS="{'host':'db','database':'proxy_py','user':'proxy_py','password':'proxy_py'}"
        depends_on:
            - db

volumes: 
    pgdata:
